#!/bin/bash

username=$(whoami)
hostname=$(hostname)
ip_address=$(hostname -I | awk '{print $1}')
gateway_address=$(ip route show default | awk '/default/ {print $3}')
macaddress=$(ip link show | awk '/ether/ {print $2; exit}')

echo "Username: $username"
echo "Hostname: $hostname"
echo "IP Address: $ip_address"
echo "Gateway Address: $gateway_address"
echo "MAC Address: $macaddress"

