#!/bin/bash

sudo apt autoremove -y
sudo apt update -y
sudo apt upgrade -y
sudo apt autoremove -y
flatpak update
tldr -u
#for kali linux
#sudo updatedb
#sudo nala update && sudo nala upgrade -y

var=$(
	cat <<'END_HEREDOC'
 ┏━┓╻ ╻┏━┓╺┳╸┏━╸┏┳┓   ╻ ╻┏━┓╺┳┓┏━┓╺┳╸┏━╸╺┳┓   ┏━┓┏┓╻╺┳┓
 ┗━┓┗┳┛┗━┓ ┃ ┣╸ ┃┃┃   ┃ ┃┣━┛ ┃┃┣━┫ ┃ ┣╸  ┃┃   ┣━┫┃┗┫ ┃┃
 ┗━┛ ╹ ┗━┛ ╹ ┗━╸╹ ╹   ┗━┛╹  ╺┻┛╹ ╹ ╹ ┗━╸╺┻┛   ╹ ╹╹ ╹╺┻┛
 ╻ ╻┏━┓┏━╸┏━┓┏━┓╺┳┓┏━╸╺┳┓   ┏━┓╻ ╻┏━╸┏━╸┏━╸┏━┓┏━┓┏━╸╻ ╻╻  ╻  ╻ ╻   
 ┃ ┃┣━┛┃╺┓┣┳┛┣━┫ ┃┃┣╸  ┃┃   ┗━┓┃ ┃┃  ┃  ┣╸ ┗━┓┗━┓┣╸ ┃ ┃┃  ┃  ┗┳┛   
 ┗━┛╹  ┗━┛╹┗╸╹ ╹╺┻┛┗━╸╺┻┛   ┗━┛┗━┛┗━╸┗━╸┗━╸┗━┛┗━┛╹  ┗━┛┗━╸┗━╸ ╹    
END_HEREDOC
)
echo "$var"
